# Generated by Django 4.1.4 on 2022-12-08 06:10

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=mptt.fields.TreeForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, related_name='posts', to='news.category', verbose_name='Категория'),
            preserve_default=False,
        ),
    ]
